### ISSUE TITLE
preact-compat@3.0.0 not compatible with webpack2

### ISSUE THREAD

**Issue by megafirzen** [developit/preact-compat#155]
I tried it with webpack2 and received following error:

```
SyntaxError: Unexpected token: punc ()) [./~/preact-compat/src/index.js:31,0][vendor__6dea1.js:53,24]
```

Took a look inside the bundled code and I spotted an un-transpiled es6's fat arrow.

Also, I am new to webpack 2 and it's tree-shaking, but is it because of this tree-shaking that it pointed to `/~/preact-compat/src/index.js` instead of `/~/preact-compat/dist/preact-compat.js`?

I tried with preact-compat@2.3.1 or sooner versions and it worked as expected.

**Comment by developit** [comment]
This seems to be due to pointing `"modules"` at src. I was under the impression people using Webpack 2 would be transpiling dependencies this way?

**Comment by megafirzen** [comment]
I'm not sure about this but since I don't apply babel-loader for files in `node_modules`, the `src/index.js` file used will not get transpiled. So when `src/index.js` goes through uglify plugin, the plugin doesn't understand es2015's syntax inside and throw syntaxError.
I don't get the error on other libraries, so couldn't they be pointing to transpiled sources?

**Comment by developit** [comment]
Pointing to transpiled source turns off much of the magic of Webpack 2. Do you know if the Webpack team is still recommending to turn off transpiling within node_modules?  There is a PR thst you might be interested in: 

https://github.com/developit/preact-compat/pull/144

**Comment by megafirzen** [comment]
I can't find any recommendations on allowing transpiling sources within node_modules. However, I have just tried that on my webpack's settings and received the following error:
```
ERROR in ./~/proptypes/index.js
Module build failed: ReferenceError: [BABEL] I:\Workshop\example pj\survivejs-webpack-demo\node_modules\proptypes\index.js: Using removed Babel 5 option:~\node_modules\proptypes\.babelrc.loose - Specify the `loose` option for the relevant plugin you are using or use a preset that sets the option.
```
My guess is my babel's settings aren't compatible with the libraries. Changing babel's settings to accompany the libraries's requirements too would be a pain, and I don't think anyone would do that.

Also, I agree with piuccio's idea on the link you sent above that the distributed code should be transpiled with the exception of es6 modules. I believe webpack2's tree-shaking only need es6 modules syntax to work.

**Comment by developit** [comment]
Alrighty, I think you and @piuccio have sold me on publishing an ES Modules bundle with transpiled code.  I'll re-open #144 and we'll go from there!  Think we should close this issue and migrate the discussion?

**Comment by megafirzen** [comment]
Let's :+1:

**Comment by mikestead** [comment]
I was running into the same issue. This seems to work for me though i.e. instead of excluding all of node modules, include the specific dirs you want babel to process.

```
const path = require('path')
...
{
  test: /\.js/,
  loader: ['babel'],
  include: [
    path.resolve('src'),
    path.resolve('node_modules/preact-compat/src')
  ]
}
```

**Comment by developit** [comment]
@mikestead nice! We do something similar on my current project but found a way to generalize it: we check the `package.json` of each dependency as they come through Babel to see if it has a `jsnext:main` or `modules` field, and turn on transpiling if it does.

**Comment by iddan** [comment]
Please reopen as current solutions aren't real solutions

**Comment by developit** [comment]
ES Modules are part of ES2015. If your webpack configuration is using ES Modules source from `node_modules`, it should also transpile ES2015. It makes no sense to support one tiny part of the spec but no others.

However, I find the number of people running into this (because `babel-loader` doesn't transpile `node_modules` by default) is increasing, so we probably have no choice but to create a strange "ES2015 module that contains no ES2015 features" bundle in dist. It makes me sad, because this is a failing of the JS ecosystem, but it's the only way around the issue.

**Comment by samuxyz** [comment]
@mikestead That also worked for me.
Great!

**Comment by iddan** [comment]
(Dumb question) But doesn't UglifyJS support ES6 (not next) features?

**Comment by piuccio** [comment]
I don't think uglify supports es6, but you can use babili to output es6 minified code

https://github.com/babel/babili

**Comment by axe312ger** [comment]
@developit yeah it's sad, runned into the same problem with my js modules. I basically solve it the exact same as u propose:

https://github.com/axe312ger/redux-storage-engine-jsurl/blob/master/.babelrc#L11

Any chance to update preact-compat soon? It is the only dependency in my project which requires extra babelization to get UglifyJS2 running for a prod build :(

**Comment by developit** [comment]
Yup yup, working in this repo today.

**Comment by developit** [comment]
This should be fixed by 61864696608477ca88faf1281433150234f97691 (@piuccio's #144 :))

**Comment by gggdomi** [comment]
Using preact-compat@3.14.3, the same error (`SyntaxError: Unexpected token punc...`) is still happening for me when running UglifyJS with Webpack 2.

I read the different issues on the matter and tried their solutions (setting `'preact-compat/dist/preact-compat'` as alias or including the path to `node_modules/preact-compat` in babel-loader) without any success - though if I get it right, we should not need these workarounds anymore anyway.

Any idea where this could come from ? Some incompatibility with another module ?
You should be able to reproduce the error by adding preact-compat to https://github.com/react-boilerplate/react-boilerplate/ 
```
git clone  --depth=1 https://github.com/react-boilerplate/react-boilerplate.git
cd react-boilerplate
npm run setup
npm i -S preact preact-compat

-> add aliases to react-boilerplate/internals/webpack/webpack.base.babel.js

npm build
```
```
ERROR in main.aa8a13b6981bf2cf99bb.js from UglifyJs
Unexpected token punc «(», expected punc «:» [main.aa8a13b6981bf2cf99bb.js:22109,10]
```

If I comment out the alias lines for preact-compat, the error from Uglify disappears.

**Comment by developit** [comment]
The error is due to this line:
https://github.com/react-boilerplate/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L88

This causes webpack to use the `src` of `preact` (not preact-compat), which is ES2015.  I'd recommend using the default (`main`) entrypoint for Preact, since it's far smaller than you would be able to achieve with an Uglify setup.
