### ISSUE TITLE
breaking with react-virtualized

### ISSUE THREAD

**Issue by ritz078** [developit/preact-compat#228]
Hi,

whenever I try to update react-virtualized data, it throws an error

```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

<details>
<summary>

error stack</summary>

```
VM7842:1 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at eval (eval at evaluate (:117:21), <anonymous>:1:9)
    at Object.removeResizeListener (http://l.housing.com:4000/searchView.js:4972:7)
    at AutoSizer.componentWillUnmount (http://l.housing.com:4000/searchView.js:2366:35)
    at unmountComponent (http://l.housing.com:4000/vendor.js:4244:55)
    at unmountComponent (http://l.housing.com:4000/vendor.js:4247:20)
    at recollectNodeTree (http://l.housing.com:4000/vendor.js:4112:24)
    at removeOrphanedChildren (http://l.housing.com:4000/vendor.js:4108:63)
    at innerDiffNode (http://l.housing.com:4000/vendor.js:4105:32)
    at idiff (http://l.housing.com:4000/vendor.js:4055:279)
    at innerDiffNode (http://l.housing.com:4000/vendor.js:4101:21)
```

</details>

. I set up a [plunker](https://plnkr.co/edit/fONsxKgDnjt120esHzKg?p=preview) of react-virtualized with preact and its working fine on first render. This is mainly an issue with preact-compat I guess. 

<img width="1342" alt="screen shot 2016-10-17 at 10 53 32 pm" src="https://cloud.githubusercontent.com/assets/5389035/19447875/fea2881a-94bc-11e6-8ad2-033fb854c8a1.png">

cc: @bvaughn - in case anything can be done from your side. This error doesn't occur if I don't change the height of the container.

**Comment by developit** [comment]
@bvaughn - curious if there's anything funky being done on your end relating to height measurement?

**Comment by developit** [comment]
Ah, I have an idea what is causing this. Preact's diff removes elements it didn't create, React's doesn't. I'll look into a reliable way of ignoring unknown children!

**Comment by bvaughn** [comment]
Hey @ritz078

I created a Plnkr a few days back that showed Preact and react-virtualized working together. Have you seen it, by chance?

https://embed.plnkr.co/48amzdx0Wkv6pja4j99j/

In Facebook onboarding all day without a laptop FYI so my responses will be few and far between unfortunately.

**Comment by ritz078** [comment]
saw it. I don't think there's any error in react-virtualized. Its a preact-compat issue. Just tagged you incase anyone else faces the same issue with RV.

btw I didn't expect your reply as I was familiar that today's your 1st day at fb. 😄

**Comment by ritz078** [comment]
@developit let me know if there's is any immediate fix.

**Comment by developit** [comment]
@ritz078 I'm thinking this might be the same issue as (and thus solved by) developit/preact#373

**Comment by ritz078** [comment]
Actually it doesn't solve the issue.

<img width="1100" alt="screen shot 2016-10-28 at 6 23 51 pm" src="https://cloud.githubusercontent.com/assets/5389035/19807051/e134ee3a-9d3b-11e6-8384-70bd32ebd29a.png">

**Comment by developit** [comment]
Ah right, I forgot this was more related to removal of non-owned nodes. Sorry about that!

**Comment by developit** [comment]
Pretty sure I have a way to make this work. Will ping you about it once I have a beta ready.

**Comment by bvaughn** [comment]
Nice!

**Comment by developit** [comment]
`preact@7.0.1` (beta) should fix this.

**Comment by andest01** [comment]
I had a similar bug with Mapbox GL. Mapbox's DOM was getting removed. Updating to `preact@7.0.1` fixed this.

**Comment by developit** [comment]
Awesome. Yeah this change should fix a ton of those little things, it's been a long time coming.

**Comment by ritz078** [comment]
Sadly the issue remains. Actually I had forked react-virtualized and commented the line that caused error so I was getting no error but with RV it still exists. using v7.0.3

**Comment by bvaughn** [comment]
Hey @ritz078,

I really want RV and Preact to play nice out of the box. If there's a backwards compatible patch I could apply on the RV side to help, let me know.

If you guys are still on the 7.0 version, I'm willing to make one last 7.x bugfix release even.

**Comment by ritz078** [comment]
we are on 8. You can see the line creating the error.

![](https://cloud.githubusercontent.com/assets/5389035/19807051/e134ee3a-9d3b-11e6-8384-70bd32ebd29a.png)

I removed it and everything worked fine but I don't think that's an error on RV side.

**Comment by bvaughn** [comment]
Oh! Sorry. I mistook your 7.0.3 reference to be about RV. 🙇

Yeah, I see the error but I don't now the implications of commenting out that line. (Admittedly, I haven't been following along super closely because I've been distracted with other things recently.) If there's a safe way to handle/catch/prevent that error- I'd be willing to consider patching it on the RV side.

If Preact can handle it, better still. 😁

**Comment by developit** [comment]
Is the auto size thing part of RV, or something else?

**Comment by bvaughn** [comment]
It started off as a for of [sdecima/javascript-detect-element-resize](https://github.com/sdecima/javascript-detect-element-resize) (because that util wasn't really packaged up to be used by RV) but since then I've added several performance optimizations to it- mostly to prevent unnecessary reflows.

**Comment by bvaughn** [comment]
Maybe I should package it up as its own standalone lib that RV specifies a dependency to.

**Comment by developit** [comment]
Could do. I only mentioned it because I tried to reproduce this issue and I felt like I was missing that piece. I couldn't get RV to break :(

**Comment by bvaughn** [comment]
> I couldn't get RV to break - Jason Miller

To Twitter! 😂

**Comment by ritz078** [comment]
I tried on plunker but was unable to reproduce. Commenting that line is helping but will see if there are any perf issues. There aren't any functional issues though.

**Comment by klaemo** [comment]
Unfortunately, I'm still seeing this issue with preact `7.1.0`, preact-compat `3.9.3` and react-virtualized `8.7.0` (using AutoSizer exclusively).
Using the webpack alias method to swap in preact:

```js
alias: {
  'react': 'preact-compat',
  'react-dom': 'preact-compat',
  'react-addons-css-transition-group': 'preact-css-transition-group',
  'react-addons-shallow-compare': 'shallow-compare'
}
```
![preact-autosizer](https://cloud.githubusercontent.com/assets/778624/20858527/d56961cc-b946-11e6-9a89-8239ae9002e9.png)

**Comment by developit** [comment]
I wonder if AutoSizer is actually moving the element? That would be an issue for sure..

**Comment by bvaughn** [comment]
`AutoSizer` is built on top of a modified (for performance) version of the detect-element-resize library. You can see the DOM manipulation it's doing [here](https://github.com/bvaughn/react-virtualized/blob/master/source/vendor/detectElementResize.js).

Let me know if you'd like to chat about it.

**Comment by ritz078** [comment]
So continuing here. [this](https://github.com/housinghq/react-virtualized/blob/6d42450979cd81d3ab74233c2907800c240cbe2a/source/vendor/detectElementResize.js#L174-L176) fixes it.

Any other error after removing this ? Not so far. Have been testing internally since more than a month.

Perf issues ? Doesn't seem so. (but maybe I missed something ? monitoring.)

**Comment by bvaughn** [comment]
Oh man! If that's the only error- let's get that commit merged into RV and I'll put out a point release.

Looks like you guys are based off of 8.2.0. RV main is on 8.9.0 now so the fix would go out as 8.9.1 - _but_ if it's important for you to stay on 8.2.0 I could release an 8.2.1 fix as well.

**Comment by ritz078** [comment]
We shouldn't have any problem upgrading. Will get this tested by tomorrow or maybe you can do a pre-release 8.9.1 beta and I can test it.

**Comment by developit** [comment]
brian that technique for unsetting the element reference is my favorite

**Comment by bvaughn** [comment]
FYI this change has been applied to react-virtualized with [78910b6](https://github.com/bvaughn/react-virtualized/commit/78910b626b3c0d31d2a791a7a3f1c0dcaa56a25e) and released as 8.11.0.

**Comment by bvaughn** [comment]
Think we can close this issue now?

**Comment by ritz078** [comment]
I think we can. 👏 we are upgrading now and will comment here if something doesn't work.

**Comment by bvaughn** [comment]
Fantastic. Best of luck

**Comment by developit** [comment]
you guys are the best
